name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: '1.10.3.1040' # Specify the Clojure CLI tools version you need

      - name: Install dependencies
        run: yarn install

      - name: Run release script
        run: yarn release
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
